### ISSUE TITLE
Небольшие замечания по лабораторной работе

### ISSUE THREAD

**Issue by ananasn** [argENTvm1/laboratory#1]
1. Вы делаете `import csv`, но сам модуль csv не используете. Ознакомиться с тем, что может делать этот модуль можно по ссылке https://docs.python.org/3/library/csv.html
2. Вам необязательно было использовать список для задания списка символов пунктуации. У вас сделано `punctuation = [',', '.', ':', ';', '(', ')', '?', '!', '"', "'"]`, но непонятно зачем вам изменяемый тип объекта. Вы же не будете добавлять туда что-то или удалять. Логичнее было бы сделать строку (по ней можно итерироваться как и по списку). Более того в Python есть модуль `import string`,  в котором уже есть готовая строчка с символами пунктуации `string.punctuation`.
3. В данном случае использование параметра encoding не нужно, потому что файл откроется и так, в режиме utf-8.
4. Конструкцию вида
```python
if условие:
   ваш_код
else:
    if symbol == ' ':
        ваш_код
```
лучше поменять на такую
```python
if условие:
    ваш_код
elif условие:
    ваш_код
```
5. Для того чтобы проверить наличие объекта в последовательности (списке или строке) не нужно использовать цикл for
```python
 for i in punctuation:                         
     if symbol == i:                          
         isPunctuation = True
```
лучше сделать проще
```python
if symbol in punctuation:
    ваш_код
```
6. Еще есть замечания по оформлению программного кода. В Python есть стандарт того, как следует оформлять код - [PEP8](https://www.python.org/dev/peps/pep-0008/)
У вас я сразу вижу несколько недочетов:
 - Вы используете kebabCase для именования переменных (например, isPunctuation), в Python для переменных lowercase или snake_case. Подробнее можно ознакомиться в PEP8 в разделе [Naming Styles](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)
 - Плохим тоном является использование названий переменных транслитом (`stroka`). Используйте английский язык.
 - Много лишних пустых строчек.

**Comment by argENTvm1** [comment]
Здравствуйте, спасибо за развёрнутый ответ и замечания) Без параметра encoding у меня почему-то выскакивала ошибка кодировки в одной из строк таблицы. import забыл убрать) Нужно ли исправленную работу ещё раз отправить вам?

**Comment by ananasn** [comment]
Возможно там какой-то особенный символ, тогда замечание по encoding снимается 👍
Отправлять или не отправлять на ваше усмотрение. Баллы я уже записала.
